name: Fast Kernel Build

on:
  workflow_dispatch:

jobs:
  build-kernel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Kernel Source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential bc libssl-dev bison flex libncurses5-dev libsqlite3-dev ccache

      - name: Build Kernel
        run: |
          mkdir -p out
          make -j$(nproc --all) O=out ARCH=arm64 begonia_defconfig
          make -j$(nproc --all) O=out ARCH=arm64 CC=clang CROSS_COMPILE=aarch64-linux-gnu-

      - name: Upload Kernel Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-Image
          path: out/arch/arm64/boot/Image.gz
